2021-03-28 13:36:24,567 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 13:36:28,016 ERROR: Exception on /admin/user/new/ [GET] [in /home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask_admin/model/base.py", line 2082, in create_view
    form = self.create_form()
TypeError: create_form() missing 1 required positional argument: 'obj'
2021-03-28 13:37:17,971 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 13:38:50,120 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 13:42:21,723 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 13:42:33,494 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 14:54:11,725 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 14:54:21,338 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 14:57:34,875 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 14:58:26,332 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 14:58:37,065 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:00:34,732 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:03:46,902 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:04:29,509 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:05:29,470 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:09:27,180 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:10:02,016 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:10:53,897 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:12:16,777 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:14:05,258 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:17:52,412 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:24:26,139 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:25:32,713 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:25:40,377 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:26:42,181 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:29:49,082 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:31:08,342 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:32:23,378 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:35:17,926 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:38:47,197 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:39:03,859 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:48:59,881 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:49:15,417 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:49:19,801 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:49:21,890 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:49:30,658 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:54:37,274 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:54:38,907 ERROR: Exception on /index [GET] [in /home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/nils/python/ldap/app/routes.py", line 19, in index
    return render_template("index.html", title='Home Page', primarygroup=pgroup_name)
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/nils/python/ldap/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/nils/python/ldap/app/templates/base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "/home/nils/python/ldap/app/templates/index.html", line 16, in block "content"
    {% if curren_user.othergroups %}
  File "/home/nils/python/ldap/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'curren_user' is undefined
2021-03-28 15:54:54,655 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 15:59:03,244 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
2021-03-28 16:00:44,203 INFO: GLauth Management UI [in /home/nils/python/ldap/app/__init__.py:48]
